### ISSUE TITLE
fails when required is used

### ISSUE THREAD

**Issue by gajus** [StefanTerdell/json-schema-to-zod#10]
JSON schema:

```yaml
  type:       object
  properties:
    id:
      type:     integer
      required: true
    username:
      type:     string
      required: true
    status:
      type:     string
      required: true
  required:   true
```

Error:

```
/Users/gajus/Documents/dev/contra/contra-api/node_modules/json-schema-to-zod/parsers/parseObject.js:15
            return `${JSON.stringify(k)}:${(0, parseSchema_1.parseSchema)(v)}${((_a = schema.required) === null || _a === void 0 ? void 0 : _a.includes(k)) ? requiredFlag : ".optional()"}`;
                                                                                                                                               ^

TypeError: _a2.includes is not a function
    at <anonymous> (/Users/gajus/Documents/dev/contra/contra-api/node_modules/json-schema-to-zod/parsers/parseObject.js:15:144)
    at Array.map (<anonymous>)
    at parseObject (/Users/gajus/Documents/dev/contra/contra-api/node_modules/json-schema-to-zod/parsers/parseObject.js:13:149)
    at selectParser (/Users/gajus/Documents/dev/contra/contra-api/node_modules/json-schema-to-zod/parsers/parseSchema.js:34:34)
    at parseSchema (/Users/gajus/Documents/dev/contra/contra-api/node_modules/json-schema-to-zod/parsers/parseSchema.js:22:18)
    at jsonSchemaToZod (/Users/gajus/Documents/dev/contra/contra-api/node_modules/json-schema-to-zod/jsonSchemaToZod.js:14:217)
    at <anonymous> (/Users/gajus/Documents/dev/contra/contra-api/src/bin/generate-zod.ts:45:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
