### ISSUE TITLE
oneOf with required fields produces a schema that outputs an any type

### ISSUE THREAD

**Issue by timgent** [StefanTerdell/json-schema-to-zod#121]
Given a schema with oneOf specifying required fields:

```yaml
$id: https://schema.multiverse.io/bad/thing/1.0.0
$schema: https://json-schema.org/draft/2020-12/schema
type: object
oneOf:
  - required: [thingA]
  - required: [thingB]
properties:
  thingA:
    type: string
  thingB:
    type: string
```

When I generate a schema (v2.6.0 of the library) I get a schema which outputs an any type:

```typescript
import { z } from "zod";

export default z
  .object({ thingA: z.string().optional(), thingB: z.string().optional() })
  .and(
    z.any().superRefine((x, ctx) => {
      const schemas = [z.any(), z.any()];
      const errors = schemas.reduce<z.ZodError[]>(
        (errors, schema) =>
          ((result) => (result.error ? [...errors, result.error] : errors))(
            schema.safeParse(x),
          ),
        [],
      );
      if (schemas.length - errors.length !== 1) {
        ctx.addIssue({
          path: ctx.path,
          code: "invalid_union",
          unionErrors: errors,
          message: "Invalid input: Should pass single schema",
        });
      }
    }),
  );
```
Looking at the code the issue I assume is coming due to this:
https://github.com/StefanTerdell/json-schema-to-zod/blob/a1773d64634d93f090e62a520fe96c23c5315b90/src/parsers/parseOneOf.ts#L14
