### ISSUE TITLE
required_error is missing

### ISSUE THREAD

**Issue by GrangbelrLurain** [StefanTerdell/json-schema-to-zod#123]
required error message is missing.
here is my yaml schema for testing.

```yaml
$schema: http://json-schema.org/draft-07/schema#

type: array
title: Hotels
items:
  type: object
  properties:
    id:
      type: string
      description: 호텔 ID (primary key)
      required: true
      errorMessage:
        required: "호텔 ID (primary key)는 필수 항목입니다."
    title:
      type: string
      description: 호텔 이름 (본제)
      required: true
      errorMessage:
        required: "호텔 이름 (본제)는 필수 항목입니다."
      examples:
        - 호텔 몬토레 그라스미아 오사카
    subTitle:
      type: string
      description: 호텔 이름 (부제)
      required: true
      errorMessage:
        required: "호텔 이름 (부제)는 필수 항목입니다."
      examples:
        - Hotel Monterey Grasmere Osaka
    location:
      type: string
      description: 호텔 위치
      required: true
      errorMessage:
        required: "호텔 위치는 필수 항목입니다."
      examples:
        - 도톤보리 근처에 위치
    price:
      type: number
      description: 호텔 판매 가격 (할인 후)
      required: true
      errorMessage:
        required: "호텔 판매 가격 (할인 후)는 필수 항목입니다."
    basicPrice:
      type: number
      description: 호텔 기본 가격 (할인 전)
      required: true
      errorMessage:
        required: "호텔 기본 가격 (할인 전)는 필수 항목입니다."
    grade:
      type: string
      enum:
        - "0"
        - "0.5"
        - "1"
        - "1.5"
        - "2"
        - "2.5"
        - "3"
        - "3.5"
        - "4"
        - "4.5"
        - "5"
      description: 호텔 등급
      nullable: true
      default: null
    thumbnailSrc:
      type: string
      description: 호텔 썸네일 이미지
      required: true
      errorMessage:
        required: "호텔 썸네일 이미지는 필수 항목입니다."
    latitude:
      type: number
      description: 호텔 위도 (지도 표시용)
      errorMessage:
        required: "호텔 위도 (지도 표시용)는 필수 항목입니다."
    longitude:
      type: number
      description: 호텔 경도 (지도 표시용)
      errorMessage:
        required: "호텔 경도 (지도 표시용)는 필수 항목입니다."
    country:
      type: string
      description: 국가
      errorMessage:
        required: "국가는 필수 항목입니다."
    countryCode:
      type: string
      description: 국가 코드
      errorMessage:
        required: "국가 코드는 필수 항목입니다."
    city:
      type: string
      description: 도시
      errorMessage:
        required: "도시는 필수 항목입니다."
    cityCode:
      type: string
      description: 도시 코드
      errorMessage:
        required: "도시 코드는 필수 항목입니다."
  required:
    - id
    - title
    - subTitle
    - location
    - price
    - basicPrice
    - grade
    - thumbnailSrc
    - latitude
    - longitude
    - country
    - city
    - cityCode
  errorMessage:
    required:
      id: "호텔 ID (primary key)는 필수 항목입니다."
      title: "호텔 이름 (본제)는 필수 항목입니다."
      subTitle: "호텔 이름 (부제)는 필수 항목입니다."
      location: "호텔 위치는 필수 항목입니다."
      price: "호텔 판매 가격 (할인 후)는 필수 항목입니다."
      basicPrice: "호텔 기본 가격 (할인 전)는 필수 항목입니다."
      grade: "호텔 등급은 필수 항목입니다."
```

I insert required errorMessage in properties and object errorMessage, but it is not work.
searching repo for "required_error" but not found.
please check this issue.
