### ISSUE TITLE
null is parsed z.any()

### ISSUE THREAD

**Issue by GrangbelrLurain** [StefanTerdell/json-schema-to-zod#125]
when I parse null value in yaml json schema to zod parsing, `null` value is parsed `z.any()`
here is example
```yaml
$schema: "https://json-schema.org/draft/2020-12/schema"
$id: /activity/entities/activity
title: Activity
type: object
properties:
  Price:
    type:
      - number
      - null
    description: |
      Tour/Pass Price
    $comment: |
      If the product price needs to be checked on the details page, it will be processed as null
      If it is processed as null, it will be displayed as 'Check details page' in the list.
```

example parsed code is here,

```ts
z.object({
  Price: z
    .union([z.number().describe('Tour/Pass Price\n'), z.any().describe('Tour/Pass Price\n')])
    .describe('Tour/Pass Price\n')
    .optional(),
```

please check is `null` type parsing to `z.null()`
